### ISSUE TITLE
Unable to modify an extended NWBFile

### ISSUE THREAD

**Issue by NileGraddis** [hdmf-dev/hdmf#354] opened 2020-05-18 23:15 UTC
## Description

I am attempting to add data to an NWBFile. The file has been generated using [this extension](https://github.com/t-b/ndx-MIES/pull/1) (courtesy of @t-b), with the spec cached.

## Steps to Reproduce

With the file:

[repro.nwb.zip](https://github.com/hdmf-dev/hdmf/files/4647335/repro.nwb.zip)

running:

```python
import os

import pynwb
from pynwb import NWBHDF5IO, ProcessingModule


def main():

    nwb_path = "repro.nwb"

    with pynwb.NWBHDF5IO(path=nwb_path, mode="r+", load_namespaces=True) as nwb_io:
        nwb = nwb_io.read()

        spike_module = ProcessingModule(name='spikes', description='detected spikes')
        nwb.add_processing_module(spike_module)

        # This is the container which is causing the problem
        dev = nwb.devices["device_ITC18USB_Dev_0"]
        print(type(dev))
        print(dev)
        print(type(dev.parent))
        print(dev.parent)

        nwb_io.write(nwb)


if __name__ == "__main__":
    main()
```

produces:
```
<class 'pynwb.device.Device'>
device_ITC18USB_Dev_0 pynwb.device.Device at 0x139619911744400
Fields:
  description: Harvard Bioscience (formerly HEKA/Instrutech) Model: ITC18USB

<class 'hdmf.build.manager.Proxy'>
{'source': 'repro.nwb', 'location': 'root/general', 'namespace': 'ndx-mies', 'data_type': 'MIESMetaData'}
Traceback (most recent call last):
  File "repro.py", line 32, in <module>
    main()
  File "repro.py", line 28, in main
    nwb_io.write(nwb)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/utils.py", line 552, in func_call
    return func(args[0], **pargs)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/backends/hdf5/h5tools.py", line 302, in write
    call_docval_func(super().write, kwargs)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/utils.py", line 396, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/utils.py", line 552, in func_call
    return func(args[0], **pargs)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/backends/io.py", line 43, in write
    f_builder = self.__manager.build(container, source=self.__source)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/utils.py", line 552, in func_call
    return func(args[0], **pargs)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/build/manager.py", line 170, in build
    result = self.__type_map.build(container, self, builder=result, source=source, spec_ext=spec_ext)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/utils.py", line 552, in func_call
    return func(args[0], **pargs)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/build/manager.py", line 770, in build
    builder = obj_mapper.build(container, manager, builder=builder, source=source, spec_ext=spec_ext)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/utils.py", line 552, in func_call
    return func(args[0], **pargs)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/build/objectmapper.py", line 570, in build
    self.__add_groups(builder, self.__spec.groups, container, manager, source)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/build/objectmapper.py", line 807, in __add_groups
    self.__add_groups(sub_builder, spec.groups, container, build_manager, source)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/build/objectmapper.py", line 807, in __add_groups
    self.__add_groups(sub_builder, spec.groups, container, build_manager, source)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/build/objectmapper.py", line 823, in __add_groups
    self.__add_containers(builder, spec, attr_value, build_manager, source, container)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/build/objectmapper.py", line 876, in __add_containers
    self.__add_containers(builder, spec, container, build_manager, source, parent_container)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/build/objectmapper.py", line 860, in __add_containers
    builder.set_link(LinkBuilder(rendered_obj, name=spec.name, parent=builder))
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/utils.py", line 552, in func_call
    return func(args[0], **pargs)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/build/builders.py", line 328, in set_link
    self.__set_builder(builder, GroupBuilder.__link)
  File "/home/nile/Documents/work/allen_institute/ipfx/hdmf/src/hdmf/build/builders.py", line 259, in __set_builder
    (name, self.obj_type[name], self.name, obj_type))
KeyError: "'device_ITC18USB_Dev_0' already exists as groups in devices, cannot set as links"
```

The actual error seems like a bit of a red herring - there are some places in objectmapper where the container being written's parent is compared to the "destination" parent using Python's `is`. This allows the objectmapper to determine whether a piece of data ought to be linked to another source. In this case, it compares the `Proxy` printed above to the `NWBFile` and tries to link. I don't know why this proxy is the parent of the device printed or why it is being compared to the `NWBFile` itself.

We don't have to modify this file in-place. The changes in [pr 326](https://github.com/hdmf-dev/hdmf/pull/326) would do the trick if released.

## Environment

python 3.7, ubuntu 20.04, pynwb @ dev, hdmf @ dev

**Comment by rly** [comment] 2020-05-19 16:54
@NileGraddis @t-b At first pass, it looks like this is an issue with HDMF handling the ndx-mies extension.

While I look at resolving the issue within HDMF, one solution that appears to have worked is to remove nested type definitions from the ndx-mies extension. In ndx-mies, you have:
```yaml
groups:
- neurodata_type_def: MIESMetaData
  neurodata_type_inc: LabMetaData
  doc: ...
  datasets:
  - neurodata_type_def: GeneratedBy
    neurodata_type_inc: NWBData
    doc: ...
  groups:
  - neurodata_type_def: UserComment
    doc: ...
    groups:
    - neurodata_type_def: UserCommentDevice
      neurodata_type_inc: Device
      doc: ...
      datasets:
      - neurodata_type_def: UserCommentString
        neurodata_type_inc: NWBData
        doc: ...
```

I recommend unnesting all of these types such that all the types are defined at the root level. Thus, the YAML should look like:
```yaml
groups:
- neurodata_type_def: MIESMetaData
  neurodata_type_inc: LabMetaData
  doc: ...
  datasets:
  - neurodata_type_inc: GeneratedBy
    doc: ...
  groups:
  - neurodata_type_inc: UserComment
    doc: ...

- neurodata_type_def: UserComment
  doc: ...
  groups:
  - neurodata_type_inc: UserCommentDevice
    doc: ...
    
- neurodata_type_def: UserCommentDevice
  neurodata_type_inc: Device
  doc: ...
  datasets:
  - neurodata_type_inc: UserCommentString
    doc: ...

datasets:
- neurodata_type_def: GeneratedBy
  neurodata_type_inc: NWBData   doc: ...

- neurodata_type_def: UserCommentString
  neurodata_type_inc: NWBData
  doc: ...
```

You can do that in `createExtensionSpec.py` in a similar way:
```python
	mies_general_datasets = [NWBDatasetSpec(neurodata_type_inc='GeneratedBy',
										    doc='...')],

    mies_general_groups = [NWBGroupSpec(neurodata_type_inc='UserComment',
										doc='...'), 
                           NWBGroupSpec(neurodata_type_inc='TestPulse',
										doc='...'), 
                           NWBGroupSpec(neurodata_type_inc='LabNotebooks',
										doc='...'), 
                           NWBGroupSpec(neurodata_type_inc='StimulusSets',
										doc='...')]

    mies_general = NWBGroupSpec(neurodata_type_def='MIESMetaData',
                                neurodata_type_inc='LabMetaData',
                                datasets=mies_general_datasets,
                                groups=mies_general_groups,
                                doc='Additional data and metadata from MIES')
```

I manually modified the cached spec in the file, and that seemed to work. So I recommend unnesting the groups in `create_extension_spec.py`, generating the YAML file from that, and writing the data with the new extension. Let me know if you need additional help. Meanwhile, I'll try to resolve the issue within HDMF and/or get `export` merged.

**Comment by t-b** [comment] 2020-05-19 22:38
@NileGraddis @rly I've pushed a first unnested version to https://github.com/t-b/ndx-MIES/pull/1.

The create_extension_spec.py file looks rather clumsy I think. Can I make that better? Any idea how I should make the nested stimset_referenced currently commented out?

**Comment by t-b** [comment] 2020-05-19 23:31
Any idea why the attached file does not validate?
[HardwareTests-compressed.zip](https://github.com/hdmf-dev/hdmf/files/4653788/HardwareTests-compressed.zip)

I'm getting

```
$ python -m pynwb.validate HardwareTests-compressed.nwb
Traceback (most recent call last):
  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\site-packages\pynwb\validate.py", line 126, in <module>
    main()
  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\site-packages\pynwb\validate.py", line 72, in main
    ns_deps = NWBHDF5IO.load_namespaces(catalog, path)
  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\utils.py", line 483, in func_call
    return func(args[0], **parsed['args'])
  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\backends\hdf5\h5tools.py", line 137, in load_namespaces
    d.update(namespace_catalog.load_namespaces('namespace', reader=reader))
  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\utils.py", line 483, in func_call
    return func(args[0], **parsed['args'])
  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\spec\namespace.py", line 475, in load_namespaces
    ret[ns['name']] = self.__load_namespace(ns, reader, types_key, resolve=resolve)
  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\spec\namespace.py", line 416, in __load_namespace
    self.__load_spec_file(reader, s['source'], catalog, dtypes=dtypes, resolve=resolve)
  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\spec\namespace.py", line 384, in __load_spec_file
    ret.extend(__reg_spec(self.__group_spec_cls, spec_dict))
  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\spec\namespace.py", line 368, in __reg_spec
    raise ValueError(msg)
ValueError: no neurodata_type_def or data_type_def found in spec ndx-mies.extensions
```

with the new ndx-MIES extension.

**Comment by t-b** [comment] 2020-05-20 23:02
@rly @NileGraddis Thanks to you both the ndx-MIES extention now creates valid files again. But that error here is still present.

I've started coding up a pure python showcase showing the problem but I'm stuck at creating a custom class for one of my typedefs. Current state is at https://github.com/t-b/ndx-MIES/pull/1 all helping hands are appreciated ;)

**Comment by t-b** [comment] 2020-05-20 23:04
[HardwareTests-V2.zip](https://github.com/hdmf-dev/hdmf/files/4659670/HardwareTests-V2.zip)

**Comment by rly** [comment] 2020-05-20 23:05
I'll take a look. Thanks.

**Comment by rly** [comment] 2020-05-20 23:13
@t-b When I validate the test file in HardwareTests-V2.zip , I get the following output:
```
Validating C:/Users/Ryan/Downloads/HardwareTests-V2/HardwareTests-V2.nwb against cached namespace information using namespace ndx-mies.
 - found the following errors:
root/processing (): argument missing
```
After I manually add a 'processing' group to the file root and rerun validation, I get no errors. Could you confirm that this test file doesn't validate for the error you showed above?

**Comment by rly** [comment] 2020-05-20 23:17
Regarding the extensions showcase file, running it, I get:
```
Traceback (most recent call last):
  File "extensions.py", line 34, in <module>
    file_create_date=create_date, lab_meta_data=[GeneratedBy(name="GeneratedBy", data=[1, 2, [1, 2]])])
  File "C:\Users\Ryan\Miniconda3\envs\dev\lib\site-packages\hdmf\utils.py", line 483, in func_call
    return func(args[0], **parsed['args'])
  File "extensions.py", line 30, in __init__
    self.data = getargs('data', kwargs)
AttributeError: can't set attribute
```

**Comment by t-b** [comment] 2020-05-21 12:56
@rly Confirmed I posted the wrong file. A fixed one is here [HardwareTests-V2.zip](https://github.com/hdmf-dev/hdmf/files/4662509/HardwareTests-V2.zip).

I'm looking into the showcase now.

**Comment by t-b** [comment] 2020-05-21 14:26
So I fixed the issue.
@NileGraddis Can you confirm that the attached file works? It does work here.
[HardwareTests-V2-fixed.zip](https://github.com/hdmf-dev/hdmf/files/4662742/HardwareTests-V2-fixed.zip)

My fix was not related to change the ndx-mies extension itself but to how I add the neurodata types to the relevant groups.

Turns out `/general` is not a neurodatatype and it is especially not inheriting from LabMetaData. I've now removed the erroneous attributes.

@rly Yeah the showcase was not yet done, I should have mentioned that. I've now removed it as it is not required anymore. Thanks for your help here!

**Comment by rly** [comment] 2020-05-28 07:54
@NileGraddis Are you still having issues here? if not, please close the issue ticket.

**Comment by rly** [comment] 2020-07-29 21:02
The export issue raised in the original post is now resolved with the export feature introduced in HDMF 2.0 #388. Using PyNWB and the latest HDMF, you should now be able to do the following:

write to same file:
```python
with pynwb.NWBHDF5IO(path=nwb_path, mode="r+", load_namespaces=True) as nwb_io:
    nwb = nwb_io.read()

    spike_module = ProcessingModule(name='spikes', description='detected spikes')
    nwb.add_processing_module(spike_module)
    
    nwb_io.write(nwb)
```

write to new file:
```python
with pynwb.NWBHDF5IO(path=nwb_path, mode="r", load_namespaces=True) as nwb_io:
    nwb = nwb_io.read()

    spike_module = ProcessingModule(name='spikes', description='detected spikes')
    nwb.add_processing_module(spike_module)

    with pynwb.NWBHDF5IO(path=export_path, mode="w") as export_io:
        export_io.export(nwb_io, nwb)
```
The ability to remove items from an NWBFile and export will be added in PyNWB in the next release.

@NileGraddis please re-open if you run into further issues.

**Closed as completed by rly** 2020-07-29 21:02 UTC
Labels: category: bug
